import exifr from 'exifr';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { readExposure } from './src/lib/exif.mjs';
import { EXPOSURE_TAGS, formatExposure, mergeOverrides } from './src/lib/image-meta.mjs';

// Spec 004's EXIF path, end to end: the allowlisted reader, the
// wall-label formatter, and the sidecar override merge. The GPS fixture
// is generated by scripts/gen-placeholders.mjs with a real GPS block so
// the allowlist assertions have something to catch.

const fixture = (name) => fileURLToPath(new URL(`./tests/fixtures/${name}`, import.meta.url));

describe('EXIF reader (T303)', () => {
  it('the GPS fixture really carries coordinates when read naively', async () => {
    // Guards the allowlist test below: if this ever fails, the fixture
    // no longer proves anything and the leak tests are hollow.
    const naked = await exifr.parse(fixture('gps.jpg'));
    expect(naked).toMatchObject({ GPSLatitudeRef: 'N', latitude: expect.any(Number) });
  });

  it('reads exactly the allowlisted tags from the GPS fixture — nothing else', async () => {
    const raw = await readExposure(fixture('gps.jpg'));
    expect(Object.keys(raw).sort()).toEqual([...EXPOSURE_TAGS].sort());
    for (const key of Object.keys(raw)) {
      expect(key).not.toMatch(/gps|latitude|longitude/i);
    }
  });

  it("returns exifr's real value shapes: numbers, and a Date for the capture time", async () => {
    const raw = await readExposure(fixture('gps.jpg'));
    expect(raw).toMatchObject({
      Make: 'Fixture',
      Model: 'Fixture FX-1',
      LensModel: 'Fixture 24-85mm f/1.8',
      FocalLength: 35,
      FNumber: 8,
      ExposureTime: 0.004,
      ISO: 100,
    });
    expect(raw.DateTimeOriginal).toBeInstanceOf(Date);
  });

  it('a file with no EXIF reads as an empty object', async () => {
    expect(await readExposure(fixture('photo.jpg'))).toEqual({});
  });

  it('a file that cannot be opened fails naming the path', async () => {
    await expect(readExposure(fixture('nope.jpg'))).rejects.toThrow(
      /could not read EXIF from .*nope\.jpg/,
    );
  });
});

describe('exposure formatting (T303)', () => {
  it('formats the fixture into wall-label strings end to end', async () => {
    const label = formatExposure(await readExposure(fixture('gps.jpg')));
    expect(label).toMatchObject({
      camera: 'Fixture FX-1',
      lens: 'Fixture 24-85mm f/1.8',
      focalLength: '35 mm',
      aperture: 'f/8',
      shutter: '1/250 s',
      iso: 'ISO 100',
    });
    expect(label.date).toBeInstanceOf(Date);
    // The fixture's capture time is 06:41:12 on the 28th, camera wall
    // clock; the label carries it as UTC wall-clock so the site's UTC
    // date formatting prints the 28th in every build zone.
    expect(label.date.toISOString()).toBe('2026-08-28T06:41:12.000Z');
  });

  it("re-bases exifr's local-zone Date to UTC wall-clock (same digits, zone UTC)", () => {
    const local = new Date(2026, 7, 29, 18, 12, 44);
    expect(formatExposure({ DateTimeOriginal: local }).date.toISOString()).toBe(
      '2026-08-29T18:12:44.000Z',
    );
  });

  it('reconstructs unit-fraction shutters from decimals and keeps long ones in seconds', () => {
    expect(formatExposure({ ExposureTime: 0.002 }).shutter).toBe('1/500 s');
    expect(formatExposure({ ExposureTime: 1 / 60 }).shutter).toBe('1/60 s');
    expect(formatExposure({ ExposureTime: 1 / 3 }).shutter).toBe('1/3 s');
    expect(formatExposure({ ExposureTime: 0.4 }).shutter).toBe('0.4 s');
    expect(formatExposure({ ExposureTime: 2 }).shutter).toBe('2 s');
    expect(formatExposure({ ExposureTime: 2.5 }).shutter).toBe('2.5 s');
    expect(formatExposure({ ExposureTime: 30 }).shutter).toBe('30 s');
  });

  it('aperture, focal length, and ISO', () => {
    expect(formatExposure({ FNumber: 5.6, FocalLength: 24, ISO: 400 })).toEqual({
      aperture: 'f/5.6',
      focalLength: '24 mm',
      iso: 'ISO 400',
    });
    expect(formatExposure({ FNumber: 1.8, FocalLength: 85.5 })).toEqual({
      aperture: 'f/1.8',
      focalLength: '85.5 mm',
    });
  });

  it('camera collapses a repeated brand and trims EXIF padding', () => {
    expect(formatExposure({ Make: 'Canon', Model: 'Canon EOS R5' }).camera).toBe('Canon EOS R5');
    expect(formatExposure({ Make: 'NIKON CORPORATION', Model: 'NIKON Z 8' }).camera).toBe(
      'NIKON Z 8',
    );
    expect(formatExposure({ Make: 'FUJIFILM', Model: 'X-T5' }).camera).toBe('FUJIFILM X-T5');
    expect(formatExposure({ Make: 'Leica \0 ', Model: '' }).camera).toBe('Leica');
    expect(formatExposure({ Model: 'X-T5' }).camera).toBe('X-T5');
  });

  it('a text capture time falls back to the EXIF colon form; junk and absent fields are absent', () => {
    expect(formatExposure({ DateTimeOriginal: '2026:08:28 06:41:12' }).date).toEqual(
      new Date(Date.UTC(2026, 7, 28, 6, 41, 12)),
    );
    expect(
      formatExposure({ DateTimeOriginal: 'yesterday', FNumber: 0, ISO: -1, ExposureTime: NaN }),
    ).toEqual({});
    expect(formatExposure(undefined)).toEqual({});
  });
});

describe('sidecar overrides (T303)', () => {
  const exposure = {
    camera: 'Fixture FX-1',
    lens: 'Fixture 24-85mm f/1.8',
    aperture: 'f/8',
    shutter: '1/250 s',
    date: new Date(2026, 7, 28),
  };

  it('a sidecar string wins verbatim, field by field', () => {
    expect(mergeOverrides(exposure, { camera: 'Leica M6', shutter: '1/125 s' })).toEqual({
      ...exposure,
      camera: 'Leica M6',
      shutter: '1/125 s',
    });
  });

  it('a sidecar date replaces the capture date', () => {
    const date = new Date(2025, 0, 1);
    expect(mergeOverrides(exposure, { date }).date).toBe(date);
  });

  it('empty strings, non-strings, invalid dates, and unknown keys do not override', () => {
    expect(
      mergeOverrides(exposure, { camera: '  ', lens: 42, title: 'x', date: new Date('junk') }),
    ).toEqual(exposure);
  });

  it('with no EXIF at all the label is only what the sidecar says', () => {
    expect(mergeOverrides({}, { lens: 'Summicron 35', iso: 'ISO 400' })).toEqual({
      lens: 'Summicron 35',
      iso: 'ISO 400',
    });
    expect(mergeOverrides(undefined, undefined)).toEqual({});
  });

  it('does not mutate its inputs', () => {
    const before = { ...exposure };
    mergeOverrides(exposure, { camera: 'X' });
    expect(exposure).toEqual(before);
  });
});
